name: mobile_coding_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_i18n: ^0.36.2
  flutter_launcher_icons: ^0.14.3
  flutter_localization: ^0.3.1
  flutter_native_splash: ^2.4.5
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0

dev_dependencies:
  analyzer: ^7.3.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.5.0
  json_serializable: ^6.9.4
  pretty_dio_logger: ^1.4.0

flutter_launcher_icons:
  image_path: "assets/png/icon_launcher.png"
  android: "launcher_icon"
  min_sdk_android: 21
  ios: true
  remove_alpha_channel_ios: true
  background_color_ios: "#F2C94C"

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/icon_launcher.png

flutter:

  uses-material-design: true

  assets:
    - assets/flutter_i18n/
    - assets/png/
    - assets/.env
